name: ardent_sports
description: A new Flutter project.

publish_to: "none" 
version: 1.0.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  page_transition: "^2.0.5"
  json_annotation: ^4.4.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  get: ^4.6.5
  fluttertoast: ^8.0.9
  webview_flutter: ^3.0.4
  flutter_easyloading: ^3.0.5
  dio: ^4.0.6
  image_picker: ^0.8.5+3
  rename: ^2.0.1
  modal_progress_hud_nsn: ^0.3.0
  cached_network_image: ^3.2.0
  dots_indicator: ^2.1.0
  razorpay_flutter: 1.3.3
  url_launcher: ^6.1.6
  confetti: ^0.7.0
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.2
  package_info_plus: ^1.3.0
  version: ^3.0.2
  google_fonts: ^4.0.3
  provider: ^6.0.5
  firebase_core: ^2.7.1
  sms_autofill: ^2.2.0
dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_test:
    sdk: flutter
  socket_io_client: ^2.0.0-beta.2
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AARDENT.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

